
spring:
  application:
    name: User
  datasource:
    username: tutiendaonline
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://localhost:5432/tutiendaonlineUserAuth
    password: udemy
    driver-class-name: org.postgresql.Driver
server:
  servlet:
    context:
      path: /user
  port: 8081

jpa:
  properties:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true