version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: userdb
    restart: always
    environment:
      POSTGRES_USER: 'roott'
      POSTGRES_PASSWORD: 'udemy'
      POSTGRES_DB: 'userdb'
    volumes:
      - userdb_data:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Usa un puerto diferente si el 5432 ya está ocupado en tu sistema
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge

volumes:
  userdb_data: