spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5434/costumers_db
    username: postgres
    password: udemy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8892

application:
  config:
    costumer-url: http://localhost:8895/api/v1/users
    products-url: http://localhost:8891/api/v1/products