version: '3.8'

services:

    db:
      image: postgres:16.1
      container_name: db-tutiendaonline-user
      restart: always
      environment:
        POSTGRES_DB: 'tutiendaonlineUser'
        POSTGRES_USER: 'root'
        POSTGRES_PASSWORD: 'udemy'
      ports:
        - '5432:5432'
      
      volumes:
        - db-data:/var/lib/postgresql/data
volumes:
  db-data:

